### ISSUE TITLE
[suggestion] Production Totale - Stacked Bar Graph

### ISSUE THREAD

**Issue by baylanger** [MichelJourdain/HydroQuebec#2]
Selon la doc de apex, le mode "Stacked Bar Graph" serait deja supporte.

Au lieu d'avoir la representation total en orange de type "bar graph", aves-vous essaye d'utiliser une couleur pour chaque type de production?

```
hydroelectrique - bleu
solaire - jaune
eolien - vert
thermique - rouge
autre - blanc ou ?
```

Merci.

**Comment by baylanger** [comment]
Ahhh... le total de production c'est la ligne.

Alors j'ai essaye de mettre la demande totale sur une ligne et la production en column (stacked bar) ... le resultat n'est pas bon. Je paste ci-dessous ce que j'ai fait a date et plus tard dans la semaine j'espere avoir du temps de libre pour essayer de trouver une bonne config.

```
          - type: custom:apexcharts-card
            #            stacked: true
            header:
              show: true
              show_states: true
              colorize_states: true
            apex_config:
              chart:
                stacked: true
              legend:
                show: false
            now:
              show: true
              label: Maintenant
            series:
              - entity: sensor.hydro_quebec_demande_totale
                name: Demande
                type: line
                offset: +20min
                show:
                  legend_value: false
                group_by:
                  duration: 15min
              - entity: sensor.hydro_quebec_production_hydraulique
                color: blue
                name: Production Hydraulique
                type: column
                stroke_width: 2
                extend_to: false
                show:
                  legend_value: false
                offset: +100min
                group_by:
                  duration: 15min
              - entity: sensor.hydro_quebec_production_eolien
                color: green
                name: Production Eolienne
                type: column
                stroke_width: 2
                extend_to: false
                show:
                  legend_value: false
                offset: +100min
                group_by:
                  duration: 15min
              - entity: sensor.hydro_quebec_production_solaire
                color: yellow
                name: Production Solaire
                type: column
                stroke_width: 2
                extend_to: false
                show:
                  legend_value: false
                offset: +100min
                group_by:
                  duration: 15min
              - entity: sensor.hydro_quebec_production_thermique
                color: red
                name: Production Thermique
                type: column
                stroke_width: 2
                extend_to: false
                show:
                  legend_value: false
                offset: +100min
                group_by:
                  duration: 15min
              - entity: sensor.hydro_quebec_production_autres
                color: white
                name: Production Autres
                type: column
                stroke_width: 2
                extend_to: false
                show:
                  legend_value: false
                offset: +100min
                group_by:
                  duration: 15min
```

**Comment by baylanger** [comment]
Apres des recherches, une ligne sur un stacked graph n'est peut-etre pas encore supporte.

Alors j'ai retire pour le fun la ligne de consommation totale. Ce-bas ce que ca donne... y'a peut-etre moyen de forcer un "ordre".

De plus, une echelle logarithmique serait peut-etre mieux mais selon le [roadmap](https://github.com/RomRider/apexcharts-card#roadmap) ce n'est pas supporte encore.

<img width="602" alt="2023-02-19_19-50-30" src="https://user-images.githubusercontent.com/5240348/219987335-361c89cb-a1f0-4e91-b0cb-837eddef38df.png">

**Comment by MichelJourdain** [comment]
Je trouve que c’est plus claire comme ceci.

![4A928672-D83A-4C5A-915A-1A7E83A997A9](https://user-images.githubusercontent.com/83040228/219991395-4f66615d-2a33-4667-abf8-f5a697d1b7e5.jpeg)

**Comment by baylanger** [comment]
C'etait une option et en effet, c'est tres bien - merci d'utiliser skyblue, le bleu standard sur ecran noir pas tres bon. J'ai quand meme garde pour le moment le tout sur 1 graph.

J'ai finallement mis "orange" pour la production total, le Q de l'icone de hydro il est orange.. et change autres pour utiliser purple.

<img width="590" alt="2023-02-19_23-17-14" src="https://user-images.githubusercontent.com/5240348/220008671-7313a0ed-3300-46c4-afb9-55350456eb53.png">

**Comment by MichelJourdain** [comment]
Si vous voulez partager votre tableau, je vais l’offrir comme option possible. Envoyez-moi le yaml et une capture d’écran.

**Comment by baylanger** [comment]
Les donnees de production d'hq ne sont plus dispo depuis un peu plus tot ce matin :( et j'ai des troues a cause des multiple "restart" de HA et changement de config du router. J'inclus quand meme a graph pour le moment mais pour bien faire ca prendrait un graph "complet".

En preparation pour le PR, j'ai mis plus bas la config mais un cleanup est peut-etre possible pour la simplifier ou l'abreger.
Da ma derniere iteration, j'ai retire la section en bas completement. Si c'est necessaire de garder les "offset", veut-on changer le "nom" des stats pour retirer la mention "+100min, etc".

```
}, {
    "date" : "2023-02-20T09:30:00",
    "valeurs" : {
      "total" : 30659.0,
      "hydraulique" : 27597.0,
      "eolien" : 2491.0,
      "autres" : 571.0,
      "solaire" : 0.0
    }
  }, {
    "date" : "2023-02-20T10:30:00",
    "valeurs" : {
      "total" : 0.0
    }
  }, {
    "date" : "2023-02-20T11:30:00",
    "valeurs" : {
      "total" : 0.0
    }
  }, {
    "date" : "2023-02-20T12:30:00",
    "valeurs" : {
      "total" : 0.0
    }
...
```

```
type: custom:vertical-stack-in-card
cards:
  - type: horizontal-stack
    cards:

      - type: vertical-stack
        cards:

          - type: custom:swiss-army-knife-card
            disable_card: true
            layout:
              template:
                name: sak_layout_fce_header
                variables:
                  - sak_layout_header_content: Production - Demande
                  - sak_layout_header_font_color: var(--secondary-text-color)
                  - sak_layout_header_font_size: 4em
                  - sak_layout_header_font_text_transform: capitalize

          - type: custom:swiss-army-knife-card
            entities:
              - entity: sensor.hydro_quebec_production_total
                name: "Production"
                icon: mdi:transmission-tower-import
              - entity: sensor.hydro_quebec_demande_totale
                name: "Demande"
                icon: mdi:transmission-tower-export
            layout:
              template:
                name: sak_layout_mjt_production_demande

      - type: vertical-stack
        cards:

          - type: custom:swiss-army-knife-card
            disable_card: true
            layout:
              template:
                name: sak_layout_fce_header
                variables:
                  - sak_layout_header_content: Energie
                  - sak_layout_header_font_color: var(--secondary-text-color)
                  - sak_layout_header_font_size: 4ema
                  - sak_layout_header_font_text_transform: capitalize

          - type: custom:apexcharts-card
            header:
              show: true
              show_states: true
              colorize_states: true
            apex_config:
              legend:
                show: false
            #now:
            # show: true
            # label: Maintenant
            series:
              - entity: sensor.hydro_quebec_production_hydraulique
                color: skyblue
                name: Hydraulique
                type: line
                stroke_width: 2
                extend_to: false
                show:
                  legend_value: false
                offset: +100min
                group_by:
                  duration: 15min
              - entity: sensor.hydro_quebec_production_eolien
                color: green
                name: Eolienne
                type: line
                stroke_width: 2
                extend_to: false
                show:
                  legend_value: false
                offset: +100min
                group_by:
                  duration: 15min
              - entity: sensor.hydro_quebec_production_solaire
                color: yellow
                name: Solaire
                type: line
                stroke_width: 2
                extend_to: false
                show:
                  legend_value: false
                offset: +100min
                group_by:
                  duration: 15min
              - entity: sensor.hydro_quebec_production_autres
                color: purple
                name: Autres
                type: line
                stroke_width: 2
                extend_to: false
                show:
                  legend_value: false
                offset: +100min
                group_by:
                  duration: 15min
              - entity: sensor.hydro_quebec_production_thermique
                color: red
                name: Thermique
                type: line
                stroke_width: 2
                extend_to: false
                show:
                  legend_value: false
                offset: +100min
                group_by:
                  duration: 15min
              - entity: sensor.hydro_quebec_demande_totale
                color: white
                name: Demande
                type: line
                stroke_width: 2
                extend_to: false
                show:
                  legend_value: false
                offset: +20min
                group_by:
                  duration: 15min
              - entity: sensor.hydro_quebec_production_total
                color: orange
                name: Production
                type: line
                stroke_width: 2
                extend_to: false
                show:
                  legend_value: false
                offset: +20min
                group_by:
                  duration: 15min
```

<img width="602" alt="2023-02-20_11-32-27" src="https://user-images.githubusercontent.com/5240348/220159983-a97ff0a3-2657-4caa-a129-47994e67b956.png">
